/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linecorp_aesgcmsiv_AESGCMSIV */

#ifndef _Included_com_linecorp_aesgcmsiv_AESGCMSIV
#define _Included_com_linecorp_aesgcmsiv_AESGCMSIV
#ifdef __cplusplus
extern "C" {
#endif
#undef com_linecorp_aesgcmsiv_AESGCMSIV_NONCE_SIZE
#define com_linecorp_aesgcmsiv_AESGCMSIV_NONCE_SIZE 12L
#undef com_linecorp_aesgcmsiv_AESGCMSIV_TAG_SIZE
#define com_linecorp_aesgcmsiv_AESGCMSIV_TAG_SIZE 16L
/*
 * Class:     com_linecorp_aesgcmsiv_AESGCMSIV
 * Method:    encrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_linecorp_aesgcmsiv_AESGCMSIV_encrypt(
    JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_linecorp_aesgcmsiv_AESGCMSIV
 * Method:    decrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_linecorp_aesgcmsiv_AESGCMSIV_decrypt(
    JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_linecorp_aesgcmsiv_AESGCMSIV
 * Method:    init
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_linecorp_aesgcmsiv_AESGCMSIV_init(JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_linecorp_aesgcmsiv_AESGCMSIV
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_linecorp_aesgcmsiv_AESGCMSIV_free(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
