/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

#include "gtest/gtest.h"

#include "utils.h"

#include "aes_gcmsiv.h"

// These test vectors have been generated and checked with BoringSSL and RustCrypto implementation
TEST(ThridPartyKAT, AesGcmSiv128)
{
    std::vector<std::vector<std::string>> tests = {
        // Generated by the BoringSSL
        {
            "00feaf0cfae02de5c2839d34de128253",
            "4e87ebd850e3b10bd0a1b343",
            "",
            "",
            "fe10975f1cb31e61d4c17e0817966e35",
        },
        {
            "b0f1780e9d3ad0dd94e79c25e346f27d",
            "dea09ba3c915ec34adc6c575",
            "",
            "f850763590d65222c938401c0d3955b0",
            "b3c2298fe83f1a6cd2d32fc7ecec38e647d71e98e73dc887718b71a567b8ffd3",
        },
        {
            "11e784c1ea5450e3b06daef9648cc318",
            "608f96f01e61b17dd9fb7fd7",
            "",
            "561c19fcc1a108c2e68677079595a2d9cafabd23c14817a6ac8a1c5dab1616c0"
            "6028d9d9937c6aaf8d19d5ca001208baa85e5c60c1975ae6bd3e4b8c024dea4a"
            "0bb449ea72b2fe97ec68dec85ee9dc29aff331ad098daccc1a2b72cb5610418a"
            "9fef00aaea96b10db86bd0cb1b502276696699ee8be837b7ae6e12d4565129ce"
            "0e25a4b7c93c204659a7c129f09e7442c80d8956c3ce17a7bcd3af6b308697f7"
            "388f433c383c02481e67824679f52f5295ed6b694a1993ecfbf02fe420ccb3f5"
            "51b5a46541fa67942af4b107d876b7a8f329f48b183761071a26fbab7be2278a"
            "8647cb80a0a7f8b74adab9079ae0bf6a0e0c6c284ce87373a0fd67008c327bfe",
            "310e41b353e8b2c0980afab5b519b543cf3527da87fb00fdefd31b0d1c0ea364"
            "123a1cb778add77512670cf840fa2333cf940138e846530e3d8c0819d2958c12"
            "fe16f8811bd880315f34455d68103464187bddac16072470e3a73bb9494f758c"
            "e8ae8057bda8da4bcb6af8632320fff36a123236b0a1ed89deb456bbdcc97c4f"
            "dd67c904de38e9bdb5ba36eb6ad6c53fcc34f8392192dad605fa059ef9afb442"
            "7d7829df6804a3416073e86a4df228b84421eed3d94f79ea53ce2cd3bd83d33c"
            "1655c2164d1fc7e3515f38663b331ca62eb7eeff3d19d17ff4d9b11f637c4a33"
            "68468020af77f5e61ae276947185af5485590a365246c81712a39ae3a1ace321"
            "3db11836ed5fef6a7e0d01b5842e3b2c",
        },
        {
            "6ffeb171b679cc5f28a7e89c45567294",
            "b66f051b65da53908b82b168",
            "692c6d51762b1ce281cac1d7e7bda57f",
            "",
            "972f0a988fe2ca9caaea832c02b96c73",
        },
        {
            "8d98573c97b23e13865924c2e1a80d5b",
            "60db465ed6d11b93f8ba4ad7",
            "10f9c2842b7d15d4fbb7744fbc3de2f2",
            "7bd3a7fc35501a45bfb26a6512367818",
            "42fdfe3e4ba0d1489d614b8313de39f36f1b45a6fa38ee7228294a3f101861fb",
        },
        {
            "800a0d5bf0ed6364bec728d1d60ab339",
            "53ec22a276cf0c01e8333525",
            "261f0ae9a57371333fec26e4f62e4d54",
            "42b9e474117bf3183b5aba7ffaddaaae3c270eeb648d28c19be74ce3be3f5032"
            "f14a5eff822e0b1eaee6722d18e976e9685ec75d1d7ab5fc72049967232e2368"
            "5d09a03afb24ee532cc8b2c9fb27722fc2550e5523c55b478dd71c510eb798a8"
            "b29efb1baa9c6722715bcf19579adfe0c38b06bd107cea3393e2280423076717"
            "1ab34e723397d922df8b3b249e5794dda5cd49bcc8a5495bd3076b426fb6b5f7"
            "8badba6bc65a6501e3e536f0f80920c28feff341a7cd617500490be0965cebc2"
            "60089b30f5812f4b9ce4c38e39b8e754906f0c2584919103a051acb310efff0c"
            "23fe22e0f17e752bfc2dcd9b4175d1ea2bd1b73e76904acfed571c7aa17c7535",
            "d8aa57ae60bc1d20415e3e7e12a3edaf1b07543ca333739f2ec93505b187531d"
            "e3390df1052a5d01171a5febd7d582c428e42ff5e1e1d3d9c888e575fe6e77f1"
            "f0c2676c7d03703a7ad0e674664f533bebca7f15c5f31a376c27ae48d96863aa"
            "7547f2683b35fc15aef128d84a40824e12e3b824a26f9f4a9ad4b01ff8961591"
            "161257d802d9c90c3f2a02d0248974f515537da320c287019f767b9fece9abac"
            "a6afe9c016fab6d94ed8fa2f9701d67ff1f8088979e13284c16e608a85c325fc"
            "e428f768ab93075cf17266dc1f44f47241e305454db57ac06a7884ad2a4f2046"
            "a1e7b468349c1cfe27d27902cb2ee5fb9cb1060d1fc2c9d24a68a7764372fcec"
            "19864782a5d0e8f467b97a924a4969f7",
        },
        {
            "a37aec80040e209e542baf005ba4c5d5",
            "0d4f4c9ccdd8a27b66ff4678",
            "b714ec926d07ddaa91fb3f428ed342bf873b8258743fd429d4b2088371260928"
            "cec0a5e33ae883be4a3783717aaa7a9f38171c4456cd9e42f4c42c90cfd5221e"
            "e9196f724ff05485cadb7bc2eba19382eb5536e91f38842a366de233fa991e4c"
            "17cbae8d17e3bc34b7500f5a9d69b4e4e3a892ec484cb60a564c5813be943123"
            "d579510c8f6644bba6debbe6c1ffa92f2295c65adf53a5bf1c96f7e3c6dbee03"
            "12082251a5d090f7768499b353f2b2aba13742b2c01f055752de022dc0c18146"
            "03e379226b2941aebf657bdec82d1b0fcd08620942259ffd1f9718492a4e8921"
            "7df7d23601944c23cffcea9885ff40b131dfeb6303888b6054fd755cb79e98e4",
            "",
            "962aab74e68d5b75b513e25033083b65",
        },
        {
            "9c8c3c8fb8a80935a2123c3bb40a6179",
            "6d2a751c3b6a282fac2397b9",
            "209a057f5fd2ee86a09ed35dfce3f97d758136df4bbd5e822ce4fb6246603bbe"
            "78b699ec42c189843ee1e7eae9798c00af8e524a4c88ede0f72f0ceb4f9834ef"
            "1243ac23c49223a290a6852596aa9faafbb83b93b3d899a5991977ff1f28a39b"
            "cd61ec63dcf12427258e6a2de84c6bf80e7d41898ce4e8eb4fcdba91681dd057"
            "85ca8f31514ae213e8276197c10a418ce0deb8d950120cd381b103b7faffb249"
            "8aba594359f3de6c3b801b290a9e80f1f3809a01db042119fc412096931a3303"
            "37d45a7bb89fd0a95e0d2cab9b8f3f6ef144ed0b0fc017f7fe359ae4e16b590e"
            "db065234a8241a32f9a762c7e0af2f869a0c0e077d74eb7b590c3d66213c5385",
            "5218b38a01dba4beee6e8795afa65fd8",
            "efa44019d3c0ca9357f1b45c0154b14f9eb7f038b7cad2ea2f673e4ab938aa4b",
        },
        {
            "e016f1ce32989e2eebe63b3cb3844909",
            "471cd18c31e48c2766daeeda",
            "3b4d8b36fe4aa8e1106dc5aad135d84bef579d9b45a02fe9ad303dac4f46ef43"
            "43fcecd7003172c1735058cd2513656577ba23b9d4d1b97078b74b023daa8e16"
            "624793d1fc82c41be8bf665d36074ef4d178f6359ac58fc655c2c84ffce0df71"
            "3e68b7374cdb1bb38e7dc4e8c2e665eadbafa1b720b52528e2b5869151a17967"
            "db6625475fa5f095d8bec5d91670604acb95b4c2957678f051df371c20e960d8"
            "a17b92145583ac5ff2e3f11af70d03b4ea88f407e04d3eacd950689fc93b956e"
            "14ea7e2b35cbc63f0369f4c22ce2ce3c2e780741ad65596b6c2f2d6e156e3818"
            "ef63baf13ce0c4b2a9886384379e22db568e11a23e6177f1beed38ffa58802c4",
            "47964609cde3183cb464009c8f110742d51a0722d40eedfdbc345d3f7e9f5ec7"
            "c4b28a0d6776947d09c8f18b0f1cf523ba7bda122349b2d0794ef4db2ed7083a"
            "968e4524e2f7d3bfe8630724a0624c2a6d714aaaf53522f9658b1ca39846f98f"
            "ce996c0a3c0b68a686f18eb5c7166c71271d831559e9eecae48396bcbde7709f"
            "fe464ad9f4b798a998b2dfc427d3cb82b29a152e122a2e63abd0d9cf385e9900"
            "64738bad6d4ef8af5a0670bb3dd2e43ad641e4d3691ddb21729b4a8a33921081"
            "f594ea74fedd344f05bce46d74e7ff646ab2b4268ff8c03c8563235f893688cd"
            "b50a221cb612e49de703edf014a86cff04467de87e37a966b85b88865d93bf83",
            "cc16fea89ffb94646935794e3137143972908e8c25ce95c50b9a60dd5ffb40f1"
            "10a5b0e89b18ad46cfe1bd6c4490e6f30340dff9cd82e64092c2998eeece4c92"
            "3807f6da0e6cf336a706de026407cb8dac23af410925474c7017fa054d686316"
            "2922ef9087e4c26a2f6b254967106cf407d28ac286f4b2c53de59d84a8e20674"
            "3aa536b3c9e861381701e108a5499351128192bb0f157225722d00bbfb293235"
            "e9d01970c855cdb03781b85554049afd7f9f575fc3e3807727c5d44692b45ec4"
            "1371f9a622fd19ace14f4156226d8a8fa063f2b97d62dc08df61cf70f4b74b5b"
            "78204283e795a322b376b5ea5eaa4775ad7d6dd4e684031bb33f8546a5e3528b"
            "11e974213b8296e3aa69a4cbb2b57e5a",
        },
        // Generated by the RustCrypto
        {
            "0890933b449a33e4fd68a520804bef1b",
            "bbb99211d5ddfda663f35b71",
            "",
            "",
            "3721fd2f5f895d24950a896d2078fa32",
        },
        {
            "a0c47fbe73c32acb3279680c13bffc21",
            "a4729ff943ff966292ce8379",
            "",
            "f5051e02fcf9b1c4",
            "262a8540bfee2d6f165d75dab03e3a9151eb1b5b8b9b2ceb",
        },
        {
            "853086a8474f66fe1e9c0abfbddc4eff",
            "3030abcd5cb71048577ac7af",
            "",
            "ca4ff9d2497a5ff98f78c6a0258d143a",
            "4bb780c1cac3e85d5f623723fcb041ae5c96b757373c184699bd8a7f0a35d186",
        },
        {
            "5bcef2f34a543b5713e23d5f398bcb25",
            "de7bdffba7918aea6a4b2435",
            "",
            "5350f42430210203b7f5a51d2eaeccaa4f3103522c531706",
            "58bccccfa40c6da9d545d7e0c857e774567ca832facdfd8c3c8679a50b923c3e"
            "d9c5e552f395a37a",
        },
        {
            "8afaaad9e97fe55191b17b5bb6330e1b",
            "1bb2e444b0692341b9d3e308",
            "",
            "3338a8ea4072d6dc1200c0652050b5d7f98c620a96690704e5746a8c871ce410",
            "75f660a30d72db21593f8ebfd5ad6bd9486e6312aed4e0577e8dcd824def9c6e"
            "9105bfef85c8f4e0cf80f908d0db427e",
        },
        {
            "28506fc57cc747b1050024e3c37cb006",
            "d47c4ab95c331f557f84e637",
            "",
            "1b1565fbb34da6b3d3ed5b18a8548a4a1ce75ebca263f53c52fbce519e4ce2b7"
            "cf92c16dac50ced6",
            "5d023113666cf327109d47ec3e2e1fa991fa10fa4421393848a0a4957aebe2a7"
            "134cb51e74e2b0bb4b8048f576ebba1f56c96b96cce6ba12",
        },
        {
            "a99027462883c4823547b2c5d14ac478",
            "3f1d4293b8954f55db7d7e70",
            "",
            "7e39bb020cc4147c941a689d613e86ecd25462985051e10e1ca99d7b96ff1235"
            "e9a9be15b2c29f2354f769e88c5dafd0",
            "922863180d8845f48ea50f84efc11b602115b7de42c7c5201a9b840930273a93"
            "6a92f2e528b87df16314b118138a4c18061c991aa0ee2676ea4a1495341d89fe",
        },
        {
            "51d5e44d8ab0abadfeeee4a4aec33a0b",
            "11ca300e57a3f539750a5d7a",
            "",
            "980b9e45abbb1bf70c3f35e1442efc870c3661884d3ea75ea1dcf4f570a9c75f"
            "27b87006f7f54954a835ebfe5e19e328a74e06ec09c0ce5d",
            "a05f8f863d14ac9c86292a1f936e2527823df73ebfaa54f34978bf778c02273a"
            "505ffa5c6b910001baa5b6b7eacf74f6fedc81d146ad0ca02e964c1171d5bc6d"
            "63f4d05e88136b01",
        },
        {
            "3e0019efca7a445902ab5f3265597d8e",
            "1436198f166eb809c9ca3891",
            "",
            "9326d70c3e27b388fa46ed33a5f023ed234d0ea0d7d662775a994a26b29c1b88"
            "bbdcc61eb4b147778c417b3ddeebc3c9f516ab468870e1cf152559c4cf8d98a9",
            "a1e35286cb87e2a55ba9393fdf807b62cd01106ecdd7b55cc90c06e15767a724"
            "5bea3b36d31bef6b5884d1d03ad14a945c2f13120d5a3c29d6fc1418d676a6ea"
            "441058b4a80fce2ba71294fbb0034962",
        },
        {
            "fcf3a36f80dd7b62d4596cc651d06207",
            "61aeb52a6209d531e4755f22",
            "",
            "feb74fa9d6d75564ed2259dda8dc5a6ba175cd4fed5cd4e860b59c0aad316551"
            "1847a13d4e203c5759741ae95d627b1a4c6fdb078b20aa09bc490c8db274914c"
            "5974ab951d28cc31",
            "45e85931670e8c7cd4a459af4bfcb87c6a777794768b5caa626c28932b78323b"
            "b22d43df7e767f4292d83be8fd4b3924fa2ac64876c8b45adc95b4fb50f9ae1a"
            "c4c14b34dba8f2315bda029a13571dd1fab5935264488a91",
        },
        {
            "f94168c44115a45c89cde831c8264d6e",
            "bdd9b4c7fd08a624e632dde4",
            "",
            "d2aaa4904456478dd187d9b7babdfd789b6db376ccf37113bdc113c717ed63d2"
            "458d1da0bfe06132c889b4162162638c4e86dc236b3e9c11f9fb486be72c8b6a"
            "1dc7cc346b3279b6968270f662958fd5",
            "60d2001fede905d2c63c1dba2dd0c61d3444b275ed0c6e8f33b31cb2b4e98ebd"
            "90d304b9a832ebe3ca45a6fd4fd688e5733f753bd3721aec009221dff51b4704"
            "b82468aaf0e0a95af7c0c1263601c538b403e2a626ef4dad1bc6ad9aa88fda27",
        },
        {
            "98cb1959e251001f1e0569d324c488c5",
            "79183f7529e040a712a53860",
            "",
            "82b5bd53a493cda8818654ec649f0ee7b17e54cac300c54dbcca14b4878c17cd"
            "1c9dba469630356fa481591d342406c75d8e4e81749b0f93dba1577aa978cf87"
            "b8d1b7bba34e0bc6ef71da44306521fd1d8cb3d2c5c4bb47",
            "e6f5a12dcd274bdc5fb2321f3ddb3f95de6c5b0757a7208c5d24351164277f1a"
            "1613f78cf8e8f235fa4d12c1c81dc4019450d05926600313c0a06513bf1aa7b7"
            "5b7cf4f21e1fdd01387edd468d3f630603f00f315346e99e87a781674f6bcd19"
            "379c2a9d2d2e5a0a",
        },
        {
            "57c44d1af9c3f4f9c1cb40c187fe07be",
            "31a9c3d2cb24ec0269b84133",
            "",
            "9820e9504543e3f531b72dc91ac219c2beaf78c8b2ffe571873ee5f19b4b09b1"
            "1d28019b0a87a8d4897ba11b240752214d9e93f7e8f45ab35e5461f91a832806"
            "889ca88dfaee98058bb56fa9247051780926bd804c1b7cdeb347ac451a90a4ea",
            "2a34707f81f49babeae6d07a8dd80b3b283ebad2356b7958e1181af73e222788"
            "50463716c86476280448988d24155a4338b001bd735f206f4f1f9001d7957e0a"
            "e64f3e2467d2141bf9aef3ac16c1b55194e0b3c1614bd33c700967a3f45f27b1"
            "18338ad482f05b2bef116c52e7042567",
        },
        {
            "ab25f0c5ee8c53d4cebb02139bac628d",
            "fe8039ee292ef7728df64a32",
            "",
            "9a197a6ccbbc49789f0a3a3bb540e3fa19118398f761f530fb5e01cc393bcab0"
            "772bca4f1825e894ba1bde34fa6fbbb7130d46f055d32336b3991b38bfc503c4"
            "67b48b5c3b06b49f3de30ad7a0f6224d90806efcc2cc04cf37ebe3010498b678"
            "2d88a5a4a9fa3a14",
            "bfa6908c88d6790089d99c7231ea04d33ddd5464902c58cad8a4047679854220"
            "32e2cb1881e365a7ca08ea67bbb8ed2445dceb602c965c64142abbdcfc869a2e"
            "b9f06d24599173db396cea962f8ee05560d3a8545047df6ea2101e920eb6e0fb"
            "935cd106e9c01c8585179a2ac7d9f575700b034f5b80ca34",
        },
        {
            "d7ef89d1601199b182b0edae3fec9fa5",
            "f49b3f5cd6b67d57f9d4a675",
            "",
            "d9edaa6cdb430f3630d855cc6ebbad91397dfcf31938bd74ffab5af9d7506817"
            "3f83c827a0cc1622b839c0b6706d1f11c5a94c13c41de2aae7b3ac67e1699c21"
            "723ae88191a4ade7aeb6ebffc932431b1d5e0826d21d093300a44bda28c3017f"
            "88f150c249e34561aad1301f1de7a257",
            "70e0d7c3b16fb69f848aaeb62746fad590fa1b7f9d395dda0277cbf07d507713"
            "065164f67dd6822a848a22e2b628220ff16a42de48086c978fcbc22020dc6ef7"
            "5a6b93f73dedf49969aa59effc9a7cd0d268de03905723e672fc42bfb87badd0"
            "65e7b7951f22d59fa81ceb1d6f8a4f2ea4a83ee276c8a176295695fb68316732",
        },
        {
            "e419d0b22a5330d40a9caf7b93698039",
            "828e522a12ade723005c9d28",
            "",
            "ef289641355fb3b7544500cafc8d3f4d39b7893c92742c40bc8498bcf6af1366"
            "bdbc8f1f1d4f4b5c47a547df0a303647c547d218618024214d1450b9eedaa4ce"
            "aa4dcef6b18278092da6c7962e55598c7e45d6dfe4446a8ede35e9d46372b915"
            "d5a2b6e1d6bed639e98fd1588e5d0a0ed0d72d6c69e607d5",
            "d159391fe72ead4960521816020439569df950e4ffae5cf0f6dd325c27dd7aae"
            "c724f4978446e5f6f925068191811285f436cf8432ffb5d96fe6c9d2c9115f72"
            "b7095a31608849cb9c30a4b4575b24f43b7b6352f12795ac19365f97e6a67713"
            "f5816816fb5ad4b05a71baaf8e37b0cb4e818caf23b16fe5ae44ec2a83bffff9"
            "38c68ec018dd7b63",
        },
        {
            "2442282ae6847d6a7dcd8744ea312910",
            "6e835b09afaf7d8b73b59ee6",
            "",
            "0cb5066814dd457e466f23fd51fe4a66fbac1cf2e2e4587abf53a2ac7ab18adb"
            "dfc0f13e01270fce9438f8a7389060132615c7db93f3a1f978a4bc2b607299b7"
            "23179335e362fdb7d7dbd952108784dd5471aa65322f32f37fced38c2801c154"
            "022e98949d09e530080a70f5317568da42bfddf8401bb497a0cf19185a3e3416",
            "02da5506258cef23ec04efeb2481c1671901baefbc65d3d271ee0bd24b7bf528"
            "cabb646385dff7fc498e2723c3d26b0e47cb224e4c0841e14bf5edb40ce138c9"
            "cb3af6dcec4e68f19d0810502eb99e8883ac2b1a36373c30de4f38fc0051fc2d"
            "67022ef1642dd281eb894b29cead253c57ae74d125c2919af63eff8f293c008f"
            "26f1c178fb72a6880db1cf46d22c27a6",
        },
        {
            "455e23ee179d79660ea7400381dd78a5",
            "57e5b72b7f7c4e12e1c1a3ee",
            "",
            "07c44ffb7dfddd3c7659af755d9b9c96b2d01020a4dcbe3e9b92bbb2538c968f"
            "6005ea2826dc34285130f3226ca09560a3ebd879c512011153216cf4556f27bf"
            "ce00ee37ae70179691ce9329ece2a4338cb686930b20831319eee659f91e33f1"
            "819b26475eb03650643fb193302fd1a2f7c07d910a3dcbeb93a35f1d4410dce7"
            "88814e2bd42a3783",
            "4a5e00904785954c9e0e7f241f4f03e60392a72e01cb68e5629f04a8c4c71e3f"
            "9fc833277097859ecbdde27674b79065edc6804076b63b23958992dded7d0eaa"
            "53bf480423fd571dfd9217b44f78be726900a9ab70267dd852110542367084a8"
            "e94d4837092d488dbb39ec05e472733f9dba7c42460468cedaff081a9eb87a21"
            "ecc1e3582e8b46201dd23e77af47f4a4f3bbbf14ebda05ae",
        },
        {
            "9ed804963eeac7bf5fd43c8de36078ef",
            "d09ce737dc8cf87dbeee0a40",
            "",
            "7768decbebbf9053efcd16e53287f2cd71a17e7db372efe95dd11dacbfd56335"
            "5e25320bb8182a46137b667e1e7b17259e907a3c955cfbf39276cf100e460337"
            "565c62107971ac036a4112a42b827737da17dc79dee5232ab9a58be2d9eaa4c4"
            "a8d06607ef5b800536b4ed27805b0f86902145fdb771ceda6e4ccb033d084b3e"
            "43a476000ccf9f48e0430a022c449702",
            "e2c7012a426541d414748f297430600c65c797512a8225416c068770eb0bb72f"
            "29f67b2a944ff15d30e28a7cd9dd4462e2309f194012a0b357989fb172ed54c6"
            "ceb1bab4a396e087338836a35bde97342269f21d2c09b73443e057f4f061c39c"
            "892444534871f0b1d1396925d98a7d74e460dbab488759a94cdc6bcca706f81b"
            "bbde045b666c75aa4c025925eb34bfc601be52b2ca26228344df8e5ec3bddb40",
        },
        {
            "769f669a7911ab589e17e544835c2064",
            "af32eaa0d40c734072e8d50b",
            "",
            "c78aa698999ed08ff25df73ca4cd5915d6feaf41ebd878e74b848ae74574bafa"
            "9431967414a01d7ebcd7edffdd65bc72f74eae3be00a0d2161f2c21f9254906e"
            "c678b908169bf0b791c050954b186d6332fa92a723f55c4c2f6b9fb45f898c7d"
            "97001ee31a8f91ffea389fc9c3024701680b77b7c9f5201f746a30105293237d"
            "87ddb2915eddc1618aae81c002868175db7d53425115bdc6",
            "f803267c55ee3e70afabdc98517860a0fa6cec28a7327d949500dbad72b49285"
            "7659b5f6cd969224a5c03e60ab16a080192fdc1699aec07ea69607a96e5d1787"
            "1d7914a1a5bb5c95fda97ce7280624fb9170e77a6fd5f71f8a589b76e154d5cd"
            "fc8d9648e00f85cf0caa0a501c04cd1813fbfc335513186ff7a9c181f1241c6a"
            "9ab5daf57926171d54fba5a3a1906b698027b5ae81e0c9508eba6616c4ecdc51"
            "9191bca10012cb60",
        },
        {
            "3368bdf50d525af1eb5ad3732f3d0a09",
            "dfe1d56ac472d8b87fc72696",
            "",
            "d300fd94a7f7d3adee8cf8fcb62dd7dc46fd4b4415b79519a9a33f91ec6fca12"
            "f949cb1ebdf342c2b46f708b2ba14a0cd4b7a770d456a9953cb4be511391baf8"
            "e39df8e677b9adf13f5421229f93ba22deed5bb586c290d958b0210eba1cfc85"
            "948516995cabd14ba8178018487a7cb5cdc02083d0fc1ccbb4e3a71423d4e2f5"
            "6e8132207211a64d6a368e1991b7ecd63ac4b22fff0fb74f47a773e593bd43a8",
            "ecb788b729712136e7a6d163c7078e2f91d9d7daefdbe25d3ae000a57689de2d"
            "5dc3f1dbc002b990f4d4bde8d32a29181c123e4e27fa322e4a02a03d782789d0"
            "b454d7b3a03e588068f05e3766511ff3bf9b251dd8ea38e971a49eaaaacd5e6a"
            "042761de5cc59b949c0c66502ad9bf43ffc3300e9159c40e667c51b67ab69824"
            "75015d0be4b37b0eafbed8f1e5ed51d7f7f2783f84cff3bc8613c977c5ac0327"
            "f3376b540138312a119001ffada7b37b",
        },
        {
            "5928b1d5d1e89cfe7aa4ac04734e1de4",
            "215d7156682acc80d7c55038",
            "",
            "c0805ef78226e2de3bc14d596e10f53a9f4859a471eaf6a1b95bf1203acce4db"
            "59de83720727286da01a185d220ca032c624027500e86717f89c4d51346470d3"
            "4633ca2aabf05d0a852fda2ac1aec14c5b2d2d9116cfe39483d31d91a8b7210f"
            "ce06686f5c66c5f544a703405250cc68366dccd1aea249cc705482128929d93f"
            "7e3e94fdd73caeb9f648eaaef4a3979ba04a2f2acff0820b1d9b849949ca1864"
            "72f452f5caaf7a8d",
            "ed8b6ea8e9655228d99f85aa25a0fb610de19ffe8086bd39f1ff74d3f3baf750"
            "42486349e3697b781433c425e77882ff2d4f07c6717a72a6b27c0538fc50a4da"
            "7f42159ec88ca16fca32dd20ff697601bf10f8695ee4197325328ae413645c89"
            "f6d9505f3692f758f6144f101cce4eedcf7b178eab8930f757c8ab1d714e20d6"
            "653a29b21cb798b7518c9ffe2bbe452ad4d4464e4ff39141d732ea704deb8f5a"
            "d2d5369fa6e6fb5fac603e697db04e50831c4c16dbf7aa1c",
        },
        {
            "86b7d90454796013a20a09578e694379",
            "822c13c6ff78dbfce99793d2",
            "",
            "1ffeccbf2a04ef5d6cc8eb98776b62034250eac6a68e9db0a69e4fb05bc93687"
            "17b0896da4d5fd89b325b83ae186031aefcee378ff1d8aae37462502c77617fa"
            "fcbe354b60160f254d349dc8bbad115b1bf0926069b24220b79fdfeab4daf6d7"
            "4bf1c323dc6c512bfe15b781fe0b805b3993b8d818788773f090dfaca2cce88c"
            "91ca82532c1e476cb7005e56952d5657ff7fff2ae2aaf8e1a34e3b3b763c2b01"
            "31ab01922f0263e8b7b7b58dddf34b0e",
            "07a8c48e712758a936e02dd04990da81bba8f30955a69021690063e7de00030f"
            "fd140228a1d410940ec123257017f8eb774aef37aee511ee9abfa17f009d3900"
            "e4b934e446e9e749815362490621aa6ee15d2d2b15fac17e8a89ef28f17a925a"
            "43830fdf5ee75434541ca4f7526a264dfeb86deb56a91ff52afd2abde24750df"
            "6a1def33f151afc297553cd2f14063be14b30f15e23a5d6444c08c8c027ca503"
            "120996a0d18f244f3d0ba5cc888e3bc1849be4d094e0f90e93b2d3c291eca824",
        },
        {
            "8646f82c374fdfc72463d9affdb4c5e3",
            "78b3453dc6d48d940f62314f",
            "",
            "3fb409cb0a1d2c3e3f22cda0acb3cb02612416c5ad27ea715537d25576c513f1"
            "e8bb3ef18837f6eed91d9ea9d08e7a3fd8d3615d0dc43b0837101192bfa7849f"
            "7f770f9e7d35a27eab9b541d4d233b7bdcf9cf32facdc129d47fbd0d82a52d7c"
            "018d7cc65803f43d1610db4a1b53a9d64bc849ee80ec509c88de773665558066"
            "7fda69d4faddaeeac4d1bf72bc08ee9b9e88e6c39ff4fe95494ecd448bd641c2"
            "7fbc57dbf1800fb08c14d25e94b8db43fa6d676e87776a4b",
            "4f7c20a75c56c8cf3800034f706c73b15252a0736ff115a66e8365158077c8fd"
            "614d1fbb92fc4694289aeb1505efeb885eab15dca8d5f40806dc66f32873815b"
            "e416656caa646ef989e9330a4944a04e5bcae1cd1e4f750d94c0df90a12a5db2"
            "0e9689ccc003b1c5ca8b13893fe0d5031153b032e8c02c97d50f3730433403c1"
            "0ec93c4f7e599c0150504287405a2f5215fff8183e8353e697db11f6c0550412"
            "6bbe7bb9b91903a7bf08a382510219a15bee2aadec4ec3f9f2e1df6a2139a5ef"
            "fe1f328bf757b076",
        },
    };

    for (auto test : tests) {
        aes_gcmsiv_status_t ret;
        struct aes_gcmsiv_ctx ctx;
        auto key = from_hex(test[0]);
        auto nonce = from_hex(test[1]);
        auto aad = from_hex(test[2]);
        auto plain = from_hex(test[3]);
        auto expected = from_hex(test[4]);
        uint8_t *cipher = nullptr;
        size_t cipher_sz = 0;
        uint8_t *decrypt = nullptr;
        size_t decrypt_sz = 0;

        ASSERT_EQ(key.size(), (size_t)16);

        // Allocate resources for plain and cipher
        cipher_sz = expected.size();
        cipher = new uint8_t[cipher_sz];
        ASSERT_NE(cipher, nullptr);

        decrypt_sz = plain.size();
        decrypt = new uint8_t[decrypt_sz];
        ASSERT_NE(decrypt, nullptr);

        // Init context
        aes_gcmsiv_init(&ctx);

        ret = aes_gcmsiv_set_key(&ctx, key.data(), key.size());
        EXPECT_EQ(ret, AES_GCMSIV_SUCCESS);

        // Encrypt
        ret = aes_gcmsiv_encrypt_with_tag(&ctx, nonce.data(), nonce.size(), plain.data(),
                                          plain.size(), aad.data(), aad.size(), cipher, cipher_sz,
                                          &cipher_sz);
        EXPECT_EQ(ret, AES_GCMSIV_SUCCESS);
        EXPECT_TRUE(memeq(cipher, cipher_sz, expected.data(), expected.size()));

        // Decrypt
        ret =
            aes_gcmsiv_decrypt_and_check(&ctx, nonce.data(), nonce.size(), cipher, cipher_sz,
                                         aad.data(), aad.size(), decrypt, decrypt_sz, &decrypt_sz);
        EXPECT_EQ(ret, AES_GCMSIV_SUCCESS);
        EXPECT_TRUE(memeq(decrypt, decrypt_sz, plain.data(), plain.size()));

        // Release resources
        delete[] cipher;
        delete[] decrypt;
        aes_gcmsiv_free(&ctx);
    }
}

TEST(ThridPartyKAT, AesGcmSiv256)
{
    std::vector<std::vector<std::string>> tests = {
        // Generated by the BoringSSL
        {
            "00e7188f69d6149790b3ea2c2d8c121705cb6efa52819174eec16dd363b22dac",
            "cd86b3a23d34b89d67fb1eac",
            "",
            "",
            "93b3aac7d4905f977c3819dc24bdcd05",
        },
        {
            "2927fbfa0fdc0997cecf45388fd4b4920c8c3ba3277375dce142d0d175e46b53",
            "a1fbc478579581a4e55a7315",
            "",
            "fc42a9635d1f28d414e232b84753d5d6",
            "0877edeb0fa62f69ea61808c5c086f3748491efa868493a6f7792fed37aa7257",
        },
        {
            "ebab6f2fafc590b28c25ce0eeb999cab54c38467cc6352df43c93407ff41c40d",
            "909f9a04964eb2b1c9cccb48",
            "",
            "9e8d1a593fd8b46ae4c916463e0007d6cc79c38b26c7b9fc78fbb28f41ab09e2"
            "7fb14dc72f3324eedbf515e27e2458dff82d203659e6aae248cd17ff26daefa0"
            "5db311fc18ace3e57b86f6c8fb1ddd68176038832bb0cbd10e3d5405ce97e340"
            "0aa1e599b6152104c2dde64505b58115cf13bc6502019f6f5a3c1db5ea3b9da1"
            "25ae26fd8722c0513fc1c66ccc50b2ab2cdf84d37230dbc96f7800201239dd59"
            "789602cd3f1c07297abd1f656d448dddc89695676b690b5aa73982d19008c03a"
            "509621be84cb15654c27e134c7fd38d63e9af8c847cd0cbe767ebf7eb4bc6a08"
            "9c61868a678040cb2d5c47aae8532c534c3315a8cdc0c267e8a6a7628c8f157b",
            "d61cec85e99e1e70c9c519067643409fb05252b25c72c5c66bdf63fd13833950"
            "c19c900531033aac25db7969190fed6c96e9e3a33097b6b0082ff84adf50cc1a"
            "b4e3c12c140d0144c679ce113e0dcc6ec474fee4744a1b568476ea5348001b80"
            "2f8ac047f7a4951b3d4f71bba6a780cb9d29ad71b17dce766358475932bb7189"
            "047747bc01fe1082896eda95c927f4a5995624e58ebc5fa12fcfdf3a74debbe0"
            "6ac10872528accf86fa0130a767570830b7e1e537ab4ce35717b006c461aeea5"
            "9bedbda2c633e8dd08660e0f4a983bbf183bf9b92a6c5e68f5b11f608c985adc"
            "6a37b10b36672c6ed7631aa3877722adc5ab350bfc99c60218385c19973b55bd"
            "2a56817247491500738e407ea645f23f",
        },
        {
            "1b3f6f5e303b833996cf6216a9c9db1e7b53dd31be4e4bea46e8c3fe22088886",
            "c434673ac1fcfb39085756a2",
            "7740cebc7768a716398284e1f92acf14",
            "",
            "c44a75bfc0430e14bdc2a22bcb27d7d7",
        },
        {
            "30d108e89659093ba2c224c35e16afdbb3d26d3b4ea10e324bbf22fd978f326a",
            "df0a63a829086a18e3958bcf",
            "927213d1486b4c8d1ea244781d359d56",
            "401c129754550dd2798df3ae2a22dc18",
            "298bbae14f0d1a1e29bdd6d0ced683a5dd7d2a11868e7fd9b5c0396b272d7f11",
        },
        {
            "ed56c1fc3036ac30f3117d134a4d67242ea96bb8d9c5f122dd83a6fec1ac54e2",
            "ea965ee5ca73f04cb16d9181",
            "a9dd8e98c6db8f6558b022611434afe6",
            "27adce98c44363d6e1952e0628ed5090129c660d115d60bd115a98a25fd606ca"
            "2860196b38ed43f89a37db76d4c91dadf26df8d337d22603b7e9622a690bf1c3"
            "b2251c625ec673060a5cdc772ec3ff242368343dc19e1fd76f18997d3214dc2d"
            "4e068c31d402968c5d58ad9ef8bb445478e5237c8f8724dff978a08626646917"
            "2bb3b61450e231369aa07b7cd59f29210bb9ad6cea43ce695dca71233764f48d"
            "a959596c6991b4d60d03b91ef758a003040042381881116373018daf810cb7da"
            "8380ad36135a188ec6db8928df47c5b438ed7a6db994b74f5f52884873244930"
            "6e513ad23220af116e45afe100dc5036f36ced9031dbe6dada190ef2e83ba0cb",
            "0bdaef98e76d9fb4bb0ab32c9ac79503094cc2d7deb7c7285f564a0c58b7c80b"
            "30ee5e78ba27eaff30287e274cfbdc71a66cc5230aaa2d10fbcf308bba3e422e"
            "1288f829bddf81f743a3ecaecd9d01139caad660f6e15bb44cb9b035d1cbed12"
            "17727f0463b1bb59d045f65f77f2fa4206f4bea589489bc79bf5215fed718dda"
            "f101d68ca5f1c7cdf03dc740c719e29b0a049e7733521a293537fca7c4097dd7"
            "83734b98ad71b6419e6592459615958a18fb1b818600e0fe4918ec6554fe60ac"
            "078cdf5d6d7cc781ef1064f3d998aa4a0628bce3dde6db4453f602b03196d277"
            "4bdae7ef8d3f38eefb10178c1a4fb2955b0847b1a2519ff3aca5d875e65c519c"
            "d11f1b8e1f38b745e95937c8628b863b",
        },
        {
            "b098804370bac087bb04032495685006c04a455bc8a9e879b063afa819b9f58d",
            "a550c1b07eb60eb59f6a75e1",
            "12ef51a0eb248204062cbf3f941adeaf43db8fc8bc4df7c0a39263c29b28e048"
            "f68bc0af2d124c56e2bd60ede262413a540a4ac84541a664d46aa58455fd2efe"
            "c8508ed9a834df467b27d987f47ee57d20840f23a7c0b53c511979b51fee5baa"
            "5d38407b75df4179300c4fce59d82d09a2a2714e6e5b42f245f53157b4bf80ef"
            "ae34955590ae07bd321495c5a15c0cc5357110bb72925f0924eda59bb3fb3508"
            "87b9578d04ccba2051617c3dca2800b02cf51646b926b77b7278bc0e190096fb"
            "2a1ea9f2c6ceca797dff8b00fcb40402abb1c345d171886971c1ec154eddbc3b"
            "46f4c7452dd53ffee8f63a8182adfb916aeac6f15ad0d27b1e2de77aea949ac1",
            "",
            "aadefd31162b2f23f76720f37343ea0b",
        },
        {
            "bcff24de0c11a78237ae768565d37c40107ac7c40764a2c5cf141321449d3acf",
            "6e2c5aad0e37ede37954187c",
            "875c7d20503302d5f4a68585bf2c7abd5361725b9cfd1cb94570b6af59dae9f8"
            "6be24ef8f1f514448d3cda012d02b4fc57a32f1193e326c396cf1f5a7c0329e7"
            "e2b21bf1a807a51142ac244ea261a53f1b3175f31fe9801f47def1bc89800932"
            "5350e4691c34c34d6e0ce1710fb3a9420f5b0f94735c2a5db6c7b0221ce3b7aa"
            "4be53bd92e413eec301029d40077f5a23b7594efb860d0425b28e9fb1721990b"
            "985f0c639b51c798fa6cf535b5f341c59a252c8125f8d9605c1afac87ceecbeb"
            "224b685031c1088c2935b74bdba11e308829164d19096968e0560fb489d633c1"
            "ab01443e13e66b1f30032cc036b9543446981a616f30d2cdfef6275f6f590cae",
            "c04da0da01869f497a35e08459f819c4",
            "13b9e7fd24b4b835c5a93352b77cccf19e7c17696991c359a3e6b3f69e7a7192",
        },
        {
            "e90a70b2f05c13ca0d92bbace14798df6532e3d624d9ccc41e8f3901078e7c2b",
            "f9779663657ffd199ffc6781",
            "8a86f0c0dabdcb75050db2e0b92e1b08577c36f5d91956a185d82daa05124d9d"
            "56020856b8388fd8eb259140873bbd629d5d961a23f3784922f39113b3163a2c"
            "ec311b39f9a223c35887d3cbb74460b9dbbe2bb012d7a58efa152ea6cc0e34ae"
            "bbcd3bc192ba85d82bd5c021189b3dcf9675c76ac5a8168058f695377277d76c"
            "0f29ca91e98feeebca2be8593a1b420ee962044faae3c6fe9dbf3e20af28e15c"
            "e9e8e7c1d6898206d59e57b1e590df0c711aef103ed1dbf1017dc04b63b03140"
            "daff80d8a76a9513354f983828047f0f9e80815a7b815aa448d6188479e1ac2a"
            "5d6ef6b6392a7aad591425cb0950dc3a08dcd53253699ea79f04b98a1b2d06a2",
            "9c675f29fba2609f675f649f84a9289ece3e27426423133b8242822b5562ded9"
            "96c30b63a608caaba85d4fad1189fc6dbf2464e7834aea6f601ea13799af9354"
            "b0dc53ae5f41aca67a24c50f202e9cf3e743da93eb0205d09bf26165d7adfad0"
            "f4449eb05d43934ec14b1610999f8ed96d5b35073b5c93368575ffb904e4002b"
            "e8cc699a211e5478f86cb49eec594264478469aac60f9f51b176885ac3d139c9"
            "a8cfdedc226a5972518eafaf7bfb073d5ef7e5a3868d3b7e6918e37d74f27291"
            "f70e110b4d49439599c295e65672dd30e672f7ed550ff4b49de665e0142b1098"
            "69a9041d98de2ed673a0b0b8b114cf0f7c99a511eb7f15a76ab2ce2d8ad1c506",
            "05674171214ca7f2d727935f27759d85aec2adbedb2ce8737a353a39ee1c9067"
            "c87ff9e586dc8453fc90bbe1720da201dcfa0addc0ffffaaad27666ef17cf69b"
            "3e07a388e9a69fb39f5c27fca37aed2ed781c29aabd56765511d8b7653c1cff7"
            "d573c4bc6c22ae4bb2a4178e770f247559fc197dacb61b60c0a74d3b9dcb4f39"
            "48a414e0d040ce57437ecaa54ac52d1dbd597a138cbe8c38dcfa83fb0bfcfd66"
            "d5269f239b7e38bf070210ee45fd94131080ce58eb40d7a0fc0393fd76f9b729"
            "45acf042d0eda94e203619edf0608aa01fb991a5332f8e1029573ba417015b6f"
            "8e749eb37e01a25ebfd551b339741a02c88924b1276028c2a433287819df303b"
            "6f3331fe322db32a08beb34d8cce084c",
        },
        // Generated by the RustCrypto
        {
            "e0543beb2078d2c75d5c8bc45b71db6539913d58e43350fc48ec2fc0d01b621c",
            "4a38d3e9b6f416f9c73c4bea",
            "",
            "",
            "0af4a9f1e18fba9a4ca4feef6bdb61c4",
        },
        {
            "d3cad53db70eee5b6e5623ad0d11b1b35b3fd90aa0fbdb9d7cb682e2351fe11b",
            "78abe97dde8eb158a0b8a530",
            "",
            "63c179e62618f554",
            "8e4fe8ea63e6270e76f3d7138084765b872157a3ed13e948",
        },
        {
            "7b51b2fb047e8e28bf2236b7ff13063f962f5ee751c96f252032e1702bc77dd0",
            "c5862075a4e6ec385b211202",
            "",
            "d5f4971b195465371d2455c0299a568c",
            "b69d65e6294b1d44f1e64b02fe6ad74efcf91e90bcd3734a3bc6ac518c2f6120",
        },
        {
            "67c7b679c57c50ead7cfb2ec8bf7c6a0efb888fec37357e553adf19ca13a927e",
            "5db143dd6eb394e1c5b06526",
            "",
            "adc0ab854f2acdb3d5dfe630b34261ae78208cba014cbc93",
            "d127905575e7d106ae7b4e4a22b9c16a1c335ecec22c060da0984876ef80c1bd"
            "9efae5684fb82198",
        },
        {
            "9441b21e1e86f53de02cdfd4737421385f210860e9f0788169b81838eee5d820",
            "e42ddd2e57436c8ccc1cbaff",
            "",
            "35885d0f657d34bbd777b7d6e6a24163413e446c8124d91fe42a8c1b62d78bc7",
            "6a731e897bf4ba5f695dfddf50728fb45219dee1219e520471a04974e28d7875"
            "0174929562bb91038ea0130665745648",
        },
        {
            "f8f7f1dc3c4066cb5ab9147ed7878b0e954f94b58b9a73d239558301421a0aa2",
            "cb44d8e3150152e565422e7a",
            "",
            "e68a4a5261f6d9ff3ddceb3c40d4d58fd5b3b2a41c6803a017c4a8f3dafb7ba5"
            "efc0666a1237b995",
            "9a44fd18303807223b06e8a13af1477f6cc11e97fd8abeb3546b7ee809d53e45"
            "84c9de070f2fba6c656d59abfeadf088d3ed8315aa6e987f",
        },
        {
            "d885fc99792ac341c76ab416ac4179939703863afbefa4b6fea7860a84ffded5",
            "3628513da494e31c5d0cab15",
            "",
            "9c6085140cb5067c6dad6088ec646182e04f28fb59a345986679f0a1d0b3b0c6"
            "ab50796495a7facce3996bf0d921d77b",
            "e449d0f33eff5b3a558f2e804a2a19926a16e2d32259e1c68f6c5fcf86fbcf5e"
            "6b8b3e59f242ed055be0bdea2558654142cd884c234f1f128de261b0bdf0ef56",
        },
        {
            "0e78e387a47fe32d6b813841199683e371f07dc4669f047de504f0a498d7e70e",
            "21dbc7e69e9a07a08c504d3b",
            "",
            "fe30f29e2c89700f80bd5fcf918de9adc5cef3b235c578b22683fdda86ec2503"
            "faa51f69f1db053f622a07a8a747f930fede504217761889",
            "98bf1db635d9ab46d3549c78ed8bcad3e603ff351185f6cbc7298cbe934ca167"
            "e17cfc9253e7d01178d1ce5d952472a7417aae4c2f363586e896d5178a4a6f35"
            "e35cfe7e78bc5134",
        },
        {
            "e46ef10c1cba2b8e4df2aa2cbea3cd45794b7d7b59e439c4eb6eb57d688981b3",
            "4158c3bb277173b3f5b7f68a",
            "",
            "63985e765652e850fdb99cc0126687a32770a8b54bc0f57ea5581d1aac7d2aff"
            "27cfe308eeeff33c48358d5d4f70d38bd2f4486f82da5a7e3fac54485149634f",
            "9ab3418278468e14ec39458cb9c8adba2f5ffc9c667e6c3d6416b3ca9cb2acab"
            "6230cdd579b104ae25af95f5d180d2f363862ebb3590b1688e745041560f18e0"
            "d1b7f7bce62fd32ce04134faa17196e6",
        },
        {
            "c6ab3ce9726a5bb47617b177fb06ed55e9ca97e1efd548b90db1f4ea1c8982fb",
            "bfff52ba0c6cd133bebf7329",
            "",
            "17e9e7e9f8647292a3eb90f7eb6586639ab92ece288dae62ffc5e1144896c9b3"
            "5a591af39c3af75d717cf2b6898836301a13c1d06b9db7bd9baf764624bb956f"
            "3b0f5e25c1aea076",
            "11d0eaa9cb5530efd9f100c4fc19c14e36de20502635074694ff4d722090818f"
            "2d72ce8ef56ca97a200a01585cc8d7177595749777404023f5c1d207b313d514"
            "3efb802e1d3e45c8d22e03d46de0d32cec92a2cb73c83579",
        },
        {
            "5c51d511d5e61cee971d444a75643ea8fd096b7c8ad622ce45a15d2321decfaa",
            "88196ccdae9828ae2170e9f2",
            "",
            "b0db42d510b141946178b605d524558be7e00e1d6fc873da7a8f2e3a1eca7340"
            "a88aed0f2a3729066df155337bdc756cfd706c3b6edf71a58fb994a503c3f099"
            "c1211f9fae2895f119b9701fa2f91e87",
            "97a6f3eafb98a114e971a602d20bed23cb71264c754383bb8f8f32c30c8b8f13"
            "b5f86ada810a77ec2aeb5fa5df4c63bc52fcabae1f90f4ae9d99af3c9dbbad19"
            "80e3e01c8cdf7c25ffc2bc649393dc829739d3a46b136c3106a1c83c0c3a7538",
        },
        {
            "ef311275f2f962bec0cbb21186b21378f8f75b4cb7fc4944d7e324f42b6f6676",
            "3928dc2cbf03da1ca2efad56",
            "",
            "28fd169ec097d2c1cf846903e484c0390cfc57bf336cd675da5d9b8fafa68052"
            "b67b419f1c9a90db890f0f545d7611487f738abc51f140d36d1f15600c88b013"
            "7f14a96731217808eb5f77f3d2345d451e7dc7f816374729",
            "3ca029e98be85d19481f715952ddf45d7061d4ca7decaa957e856143a1816203"
            "2f63edc78a39c2590153295b04cd396575f77269356c1dbeff4e3903b9c747d0"
            "cf28de780d99b2b2cdbe9ea9dc3d0021a0ce85910a796f3bc15e22f34921e136"
            "254cfc3979717ce1",
        },
        {
            "7dd412e6869ef93f2222679f5d6e23ad2338174ba6bb338e21c490eeed5b337d",
            "83e89678e482af4aa33d8b2b",
            "",
            "99b02d52205a5e77c616623d45533d1cd7ed796450795c95155645657e586cf5"
            "22ca7be4c7b7f3530b31a30a4fa428b5c477cc55c8b5c0a959471a103a52a6dd"
            "02b428fc76ccc9a163911d5a6f083d9da9ec3d2bdd6433b2a27462b14a4b0667",
            "948f5705e02bd0dc4ffaecd96c296ae99f666f17b6f553bd26d2c14f26fd48b6"
            "cc0664a2ea1d8717fae9520b3ffc8562ae397c94b2ea5e37e4e9cea012057990"
            "b4ac5b863ecd1cc9a658e90fc958a88796a8b1978da87e543584e9741a1b8939"
            "d36ab98cc97850781dd2685f0488900e",
        },
        {
            "63042dc9899137193be1dc0706319158f5952bf08c8fc039149ee3b4d8e0cdca",
            "481fe22c0c40eef14b834dda",
            "",
            "2d234e0a4f04847d834c90b478580a6e38d23a3b9b4454ed5cb7bd87f6d81b4d"
            "aa46e6134b286ddd6d8c4819d603a4ea52f641d284ae78f57ceac8b1e01dafe3"
            "0a4527d6c99fef9f7eca7c7678f41d8af337b0b068bb7f6a3ae69e247b8ddcba"
            "a9e3ee5d4c25a46c",
            "d23e77b7a0cf2ec85e424f526d872a61e75b123087c3b9705494659cffb93d3c"
            "d67ca849652dc181957d48ab69d410d5931768266e321fbc4d2d50710203461a"
            "28089a822d010780ecfaa4eae6e1ca7f0a77c35eca456eb07ec69d39691e9274"
            "d00d330f449c0d2ffc7a60a8a3c181a25d93db981c267f3c",
        },
        {
            "ed995d3ab1e4a6118f445d79634fb7146a70787313f50d852e1d1d08f78088e7",
            "ca8afbdbe6b20b39775741b4",
            "",
            "a9650f86d10ace973ac879db5aebadeefe24d8f97594097a1c6ca4caa4f207cb"
            "eeab4e6b4905b487ec4b73315d16818d145979d13eb6858e06ba9a9b56bce871"
            "117be496f82352de98d17979fdd80ecea771c0ccb76e3ecf4e7f949614c259f3"
            "02a3f8580c477f42bfe89c609181594d",
            "a98bedf23129c772e225f43cf430a9119d8229700eb2db0432177e2bf9a826d1"
            "79e777c191051719d189ea16ebb12f93f781a8e6ad3789e8b416aba66ff69430"
            "f78c27e2d9bb5f636c84df1396b976692026a72b549d1a76b2ae18a8a548221a"
            "3b419f79312f8059e1e7e9bee5a73bc344843d5aae4896ecdc55915c3af7f31b",
        },
        {
            "3f3e8adc7e60a9e7c4c0c415de05b2f4920b3e852696f4352539136dc1437883",
            "1568c987cfb2acf7cb2d3b31",
            "",
            "11a35ef0fef5076323ea1354c61adbcaeff45abdaaf4b1d7d2f27784ab6804d8"
            "af34c852e500ef82b397c4bcc54542bc3681fa30d570d38d8186697e94e7b89e"
            "066b2fc8c986e1bf815c269388921135ceccc44093c2663a6a3b1bee212d5fac"
            "4b8873640119b556ff1bf02330a51fcc2ce434bfd48601e7",
            "3c9ec8fe0f0c0ca416d6eb6c2ab36ed14ff2056b1db57d9e256bdd54539f7de2"
            "5b791020b55ac0f1a27b3fc0d82f7842ebcc7c4945d755f78637c38be870b6ef"
            "ff497b2e8169d674777457baa2a6c8f4186764eefddb4fd1f915721a1cbd0b4e"
            "f3b564c0a50ffd1d0c6f8ed39c98472dba97f10815f9a7cc6497df989ebc7b01"
            "484a39cdc2f61de5",
        },
        {
            "32ff95dfb317eb5b21bcc5f68ac1c192bc59582879387b952a082e72191b5b3c",
            "348eba2717acd13f1ee081bd",
            "",
            "9ff2a76b6872e179b3fc8fd16af6e5f357f9587cfa36b61e94b95052ccf5a1f2"
            "070cdb2a156a26398b0d2063b2d58fe4fb092d9c326490f8201edefd772af184"
            "082f27fc5b033d2941748bd22d82d3a4b31a23c54c89bcda9f0e32dc7e9057d6"
            "a67f80ea765f230861e453caa52cdb4f6adca052b1755121c9a50952ffc0e24e",
            "1f259be70f03db9b241dfffa6accf5971feffef36b5be1d2d1889ed673e5b83e"
            "67d6bea2d0598416df7fba061fcbbfbb6ac7edd3d86711315809f73b8f6f8c26"
            "89134623372ce2f4d39df19220699f9cbde455417b561a1bec72b79d7f11ae33"
            "aa0c79f22c35ea08a883a3fc04248f4cd55b3040c5f01c851298dcbe6b32ea93"
            "ea54016c0c56aab7c3505e4282a80c08",
        },
        {
            "e5e68fac5713a497690c04a5b1378b74b8d709cfebb53191d6ad5058e7d7f1fb",
            "9a22ff5f81fb33e456fe3416",
            "",
            "7445a34a16cc03b224de355f66eedec5bd9256543280f423e109cf56687de0d4"
            "02601c07c93a6a31bfeb88aa9bea04b60cf3be9930909df89e7024bf36007aef"
            "63e35122f4a295730f744088786516718bbbfe049229474767c91ee320c91abd"
            "c8d2f2ff0356cfd80f57d280561465090e869e52033d4baf841b2b896d858e2d"
            "bdf117affad92f51",
            "98eba096a9ec1ebd386195e748019ee18cdd343559379dcd7ef2636ad384f2a9"
            "3c0263079ea243b700f49dc57bdf5f79a5a20c014e3d917f8af69d5e19f0673b"
            "9368c2ff662add45327ee377fd9b317230f336c903ff7647289b7dbe8b9235ac"
            "2f0a76674340570af3d3c58d48a5b03a73f27ed22d18d3a1acd3faabb6603664"
            "7af5eb1a7d20ad44713abb02b5bf3db7b8d797a3757c17d1",
        },
        {
            "ba8594fa3693dd64fd1dee8516519998e64b9b4323eb8610892fe77871e5254a",
            "3585903eb572dbe435757072",
            "",
            "c5e94ec146de98391b1f9b85975ef4884971a3c858df57e38032b19f1a70fb1b"
            "47fe8afa615acb57cefaea53fe4a278c580332f15896d8dea5700d8744516738"
            "02963b6499761305293af0cab3ce6b986b2c15641b5f2a9008080559032cac7d"
            "2918ed3158c1e304180ecf3665b9173df609da17e7ed30ec1e821187e308128d"
            "bcbf628d92ba622b99289aa7898b977e",
            "6e112fb573733951f06b0608b034800387d00023f7f22fc6553bd412332e8ad5"
            "599f861c2ebd7e326352c635c21f89cea3aebb9747c876e490a3ec13aa3af205"
            "344d45c003663ad7f4589191e94d4ed170b3757f97e8c7f30de9ea36a575ea35"
            "883dec0c3b58801930a62ea4dba97d5b5177bceeb90c4e0e98dcf3147ba872c0"
            "77ca532e8fcdc409b951bcaf847220e0923ef7cdd769be0fdf691847f78abfb4",
        },
        {
            "950d8b6a171da8ffa8f354a4ab79cdf8ab7e74c0e0ef0871565b95ec8398b60c",
            "ac4a16afc6cabdf503a2e797",
            "",
            "f0cf87441193aac19037942b59cfb5dc328cecddf0ad8fc958391ebb84ebc79f"
            "aa2aaee6fb19d4981644fb73206c5f69f4ac230c0ece53d0ea6e6adcc80b761f"
            "18b508add4693eacbdbe172d80ab7f9546a35f9293eb277b3a47aea13622dea5"
            "5903fcaec5803434fd919ff1577c6f872326e2657cea2266eda0610f5eeea06f"
            "cb44aa3e7a7b87a9d73473dd05ca7b5c621a760c0a482708",
            "23b9f176ab27b4f3e683951b4e8269a147ee84cd7fc7ddff8b0a98a5f4640bea"
            "b806fb8bc2afe5ff85bfa3c758f065ac47ad767f106633041313bf4f1ce3fe3c"
            "25443055e5f85353177bc27640e6709759cf76a06dd04033e27eaff57b7cc36a"
            "e54e215d0c10c976a66ca350d3ea5224be382ae1890187e188eea3dbdd8b7077"
            "ceb9c398308270a32373d25a342a42cfc49a5d5be8a2514fcfbd53b184b31314"
            "d88fec7ed9539a1c",
        },
        {
            "c3c2171d767aba5ef8f35e82dcb17dec64881a23f9e79d4f4ddf5e87b0fb695c",
            "45c48df00d89c0989bb76d5a",
            "",
            "ba6ce5585c9539374d1cc868d47973fcce1144077f0c73463e9470230d3ea7e6"
            "0d213a29230fdda91d5a25d48fd72042a20b23f3d9896842fbb9494da1aa7442"
            "26cedd11d89becf87d087d4682564bfc45f425836ecf9ec46de5a43694d16be7"
            "e2dc825d4c177d50ef60e4c6b5d586e3774e1a0dd625aa32aec4d93902904fdf"
            "154e2369f18946fb027966eca02960969cd076c384b3656e4c83ce9d99a113eb",
            "a519acf5b1686d0abbc2b39f5cfe97b2061a2b7e0508557015053b78898dc8d2"
            "6a66d6c1ca73a5f458fc7536526df875f72407fa75ed8b6a625f9b8750e9e29d"
            "9525842d04e5ae3fbb504596fa426924752aa8dd5011922bbfc79c8366f01652"
            "7f4464d0c790fc17a6377e6fb07ef6ddb94496125a858eeee9f237f1469ce98c"
            "9be5999f7d647825dd2793121cff66b68c7dd50a5949df922bbfb1e94f8224cc"
            "ec315ea0310e07f068cabebcecd9d712",
        },
        {
            "22045f4234d0bddfeab7f0551ed119f4d5e7b4a4f3e802a1045705374240fa3a",
            "73776a263753e2570defbe6f",
            "",
            "6b43d77101de18900c9d7afe2db55c513c4f6b9aaea58d143dfee26bd48b4a00"
            "45df02624bbf325250992973ae23d27136768d527553995d564dad738dad996f"
            "7bb5cefef8e965d6e0e8b887c2c38ec6ef0b041a4275cb88d07f213ef75c1ae3"
            "ca07df0c0da3907cbf35b5672ede06bea1b5ad1fef95f17581463035c9dd532d"
            "956383f9c88986af17d97008e878b89fcd5a3d41f2807ab81d68d71d0754f23d"
            "1d981ff1e3b16de0",
            "4f32df97186aa159b69c25c122ac9240a9c5a0f8cb193593e6b6d0da6ade2df3"
            "a22f6002db5e5461dc3d1dffd3587f08ab3431e5c4f8ba85064cfd629242a713"
            "c41f26f7fed1fd95d4501bcdd0ec78e6eeeaed6483b7499795efa79ba8346ce7"
            "cb36a7625a99ae57ea95d9efea5f76f42a8a94ea622776b8221154c32d954d88"
            "31e980b8d66d166968d1d3a5b9cfdcc4abb23b56440a8e251d82f387e7f103a8"
            "727c052a2a58b7cb51ce18718d798d81502f6bfbe3eac467",
        },
        {
            "401bf964385b6f1b42e3d8306a8ecac46ca08482dffb705d55520ef1ef5ed0c0",
            "bb4f27206e210f578623ad80",
            "",
            "e0afd0432e5f12b281c7ae61a64436fcfe96a389376db4205999b2a22c4ed57f"
            "cdb47378e919fa2a0e151adb8fe6839f529809838f62ffcf22323c0fa3de9a1d"
            "ff5a49ce2877eb50869b9049bfae62cfde1465c9f1ac0447623a8dc9ccd1ecfb"
            "3e1b193df00066c91dba88565f2e982a3025232ba587f239bc5edb2275e68669"
            "526e9891a15966582abbb795f83348fa08aa055366a3b112d1b85e2f3f20987e"
            "9d37a424a6214fb83f325eef11f0040d",
            "df9ec1d3b9f9410087096996edd142ad9a189065bd5e2cba148057bda0dc78f4"
            "13e6877de5217aed4e97e02079112d4a94f8d10de91d7914130ce6fe17400d38"
            "e2486cbe0c2c906b50efe3a463ed942e60bb22dcab3905dd5c689b97a8de1cbd"
            "adf86f5211542932b909f515985c00eeb2406e63287487a6cf0724daee1cee63"
            "2171ce7e9ed245a7e683f88bfb204e451df2c6e44ac92c88f5775300aa537246"
            "9ddc09086f5db54563478590d9e4ea243f12893e0624ca2b65d5f0f594659a93",
        },
        {
            "d3a8f321cd10f29ce9fd0dc8acccde4ea32fcf780912997e7b9a7b6dd69de2a1",
            "c787a9012036552cbc453e2a",
            "",
            "b5ec98bbb7bf80daec3aa05272ed2ae5683317a821c994a9576e13eae45b870d"
            "d766a7b61d7122380e8c64cb10e21cf54f56cc38fb4a8abcdb7751515991cce5"
            "0392ae6e4b915c06ad7329a1e058d628b4e8f006e791e4a75f3980b7c2af4a63"
            "5e01cf9386dddde20931fadf51deeb301923eab4293cbfd79760779bd3e11275"
            "cd3dc3d925ff545f8c3f3187d8a627dd9bf96294c17c8591d68d9ae0f46a5eb1"
            "a155f724ceb93831c16fb36db1612e9a46d19d592b7183cd",
            "0e4c5ca8cabdbd8ecafeabe0296db7486ae4c366621f8ab2965ef7894a49a9be"
            "f79b343a201d400e7e80ac074d46b9e1f8e670934267da0abdc5659ecbb4f0f9"
            "0e92d044f80d639921e219dacee47eb54c397b87d596ef0d180ed5461b9ac0aa"
            "aeb17a682545d67c281bb1fcc9d60f5eafc6fe14703df71cc396f03881a986f0"
            "0b8e2a6d5d5febef85004bdb9ec7580b715c53a76b8596c043a7352afa3008f4"
            "561a495a650cfad3ba7ea311b2fc4078f64f59d2bdf101ccd1b5b6fdb2022b69"
            "9bcfae10d889d2f3",
        },
    };

    for (auto test : tests) {
        aes_gcmsiv_status_t ret;
        struct aes_gcmsiv_ctx ctx;
        auto key = from_hex(test[0]);
        auto nonce = from_hex(test[1]);
        auto aad = from_hex(test[2]);
        auto plain = from_hex(test[3]);
        auto expected = from_hex(test[4]);
        uint8_t *cipher = nullptr;
        size_t cipher_sz = 0;
        uint8_t *decrypt = nullptr;
        size_t decrypt_sz = 0;

        ASSERT_EQ(key.size(), (size_t)32);

        // Allocate resources for plain and cipher
        cipher_sz = expected.size();
        cipher = new uint8_t[cipher_sz];
        ASSERT_NE(cipher, nullptr);

        decrypt_sz = plain.size();
        decrypt = new uint8_t[decrypt_sz];
        ASSERT_NE(decrypt, nullptr);

        // Init context
        aes_gcmsiv_init(&ctx);

        ret = aes_gcmsiv_set_key(&ctx, key.data(), key.size());
        EXPECT_EQ(ret, AES_GCMSIV_SUCCESS);

        // Encrypt
        ret = aes_gcmsiv_encrypt_with_tag(&ctx, nonce.data(), nonce.size(), plain.data(),
                                          plain.size(), aad.data(), aad.size(), cipher, cipher_sz,
                                          &cipher_sz);
        EXPECT_EQ(ret, AES_GCMSIV_SUCCESS);
        EXPECT_TRUE(memeq(cipher, cipher_sz, expected.data(), expected.size()));

        // Decrypt
        ret =
            aes_gcmsiv_decrypt_and_check(&ctx, nonce.data(), nonce.size(), cipher, cipher_sz,
                                         aad.data(), aad.size(), decrypt, decrypt_sz, &decrypt_sz);
        EXPECT_EQ(ret, AES_GCMSIV_SUCCESS);
        EXPECT_TRUE(memeq(decrypt, decrypt_sz, plain.data(), plain.size()));

        // Release resources
        delete[] cipher;
        delete[] decrypt;
        aes_gcmsiv_free(&ctx);
    }
}
