name: Sanitizer Checks

on: [push, pull_request]

jobs:
  memcheck:
    name: Memcheck
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_flags: ["", "-DUSE_INTRINSICS=ON", "-DUSE_FEWER_TABLES=ON", "-DUSE_ROM_TABLES=ON"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install valgrind

      - name: Configure and Build
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTING=ON ${{ matrix.cmake_flags }} ../
          make

      - name: Run Memcheck
        run: ctest -V -T memcheck
        working-directory: build

  asan:
    name: Address Sanitizer
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_flags: ["", "-DUSE_INTRINSICS=ON", "-DUSE_FEWER_TABLES=ON", "-DUSE_ROM_TABLES=ON"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure and Build
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTING=ON -DENABLE_ASAN=ON ${{ matrix.cmake_flags }} ../
          make

      - name: Run AddressSanitizer
        run: ctest -V
        working-directory: build

  tsan:
    name: Thread Sanitizer
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_flags: ["", "-DUSE_INTRINSICS=ON"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure and Build
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTING=ON -DENABLE_TSAN=ON ${{ matrix.cmake_flags }} ../
          make

      - name: Run ThreadSanitizer
        run: ctest -V
        working-directory: build
